### ISSUE TITLE
java.lang.IllegalArgumentException: requirement failed: Source file 'D:\Projects\trunk\Projects\MSFITS_AZURE\MSFITS_AZURE\AzureScalaQueueService\QueueHandlerBL\target\streams\_global\assemblyOption\_global\streams\assembly\5181d4d9456869cffee25db7cf40862afd4b5731_eea687e8f56f58f889b68f00ac267b8f9e328876_da39a3ee5e6b4b0d3255bfef95601890afd80709\META-INF\license' is a directory.

### ISSUE THREAD

**Issue by champion-054** [sbt/sbt-assembly#419] opened 2021-03-11 10:45 UTC

**Comment by champion-054** [comment] 2021-03-11 10:47
This is an issue that we are receiving while trying to assemble. The license directory is causing issues. Could you please suggest the solution for this. We have been breaking our heads for a long time now. None of the answers available help. 
Thanks.

**Comment by eed3si9n** [comment] 2021-06-23 14:09
Thanks for the report. Could you provide reproduction steps so we can reproduce your problem on _our computers_?

**Comment by luisffranca** [comment] 2021-08-27 19:15
I had the same problem and the workaround proposed [here](https://github.com/sbt/sbt-assembly/issues/390#issuecomment-572868786) worked for me.

**Comment by khujo** [comment] 2022-10-12 12:11
Hey @eed3si9n,
I have created a repository reproducing the issue: https://github.com/khujo/sbt-assembly-on-windows
Running `assembly`, `clean` and then `assembly` again will raise an error like this one:
```
[error] stack trace is suppressed; run 'last assembly' for the full output
[error] (assembly) java.lang.IllegalArgumentException: requirement failed: Source file 'C:\Users\khujo\sbt-assembly-on-windows\target\streams\_global\assembly\_global\streams\assembly\919b9dff7940ba085b23a727d673b902a50cc84f_b039a2a0d771f071b57bae72e65222356693388e_da39a3ee5e6b4b0d3255bfef95601890afd80709\META-INF\license' is a directory.
[error] Total time: 4 s, completed 12.10.2022, 13:36:14
```
I was not able to reproduce the issue in WSL, so it's probably an issue with Windows only.
What if noticed so far is that you will need a dependency that has a `/META-INF/license` directory. After running `clean` the `\target\streams\_global\assembly\_global\streams\assembly` directory is still present and not empty as I would have expected. So maybe `clean` is unable to clean all the files produced during `assembly`. Hope that helps.

**Comment by martinring** [comment] 2022-10-18 07:43
i can confirm, this issue was fixed by the recent changes to in memory processing in release 2.0.0

**Comment by eed3si9n** [comment] 2022-10-18 16:39
Closing this as fixed.

**Comment by eed3si9n** [comment] 2022-10-18 16:40
Likely this was fixed in https://github.com/sbt/sbt-assembly/pull/478

**Closed by eed3si9n** 2022-10-18 16:39 UTC
