### ISSUE TITLE
shading messes up test in assembly

### ISSUE THREAD

**Issue by velvia** [sbt/sbt-assembly#172] opened 2015-10-08 06:50 UTC
I just tried the new shading functionality.  Very promising!  Unfortunately, it causes test in assembly to fail with ClassNotFoundExceptions.   For example, see my commits in this PR:

https://github.com/spark-jobserver/spark-jobserver/pull/275

If you roll back the last commit to disable test in assembly, and run "job-server/test", you will find something like this:

```
java.lang.NoClassDefFoundError: sjs/shapeless/PrependAux$
```

**Comment by ryano144** [comment] 2015-10-11 04:56
I'm seeing similar symptoms.  I am trying to use keep rules to minimize the size of my code for use in AWS Lambda.  I think what is happening in my case is that the Shading is not including for superclasses for Java classes that my code depends on.  I've had to add the following rules so far (and something tells me there will be many more): 

  ShadeRule.keep("com.typesafe.scalalogging.**").inAll,
  ShadeRule.keep("org.slf4j.**").inAll,
  ShadeRule.keep("scala.collection.**").inAll,
  ShadeRule.keep("org.apache.commons.configuration.AbstractConfiguration").inAll

**Comment by kretes** [comment] 2016-01-05 14:20
@velvia Could you confirm if that solved the issue for you? (The newest sbt-assembly 0.14.1 includes updated version of jarjar)

**Comment by velvia** [comment] 2016-01-05 23:39
@kretes I tried it just now, but unfortunately no luck, still need to disable tests in assembly.  However, the regular tests pass.   For now we might just need to disable the tests.  :(

**Comment by eed3si9n** [comment] 2016-01-05 23:49
So I should reopen this issue?

**Comment by velvia** [comment] 2016-01-05 23:50
I would think so  :)

**Comment by eed3si9n** [comment] 2016-02-14 23:55
I think this is going to be fixed by #197

**Comment by velvia** [comment] 2016-02-15 06:04
Thanks, looking forward to the next release.

**Comment by eed3si9n** [comment] 2016-02-15 06:06
I released sbt-assembly 0.14.2 a few hours ago if you want to give it a shot - http://notes.implicit.ly/post/139334060734/sbt-assembly-0142

**Comment by YuvalItzchakov** [comment] 2016-04-05 14:06
For anyone wondering, this does fix the issue!

Thanks alot!

**Comment by YuvalItzchakov** [comment] 2016-04-06 07:59
Shading now works and testing compiles fine when assembling the JAR. Problem seems to be is when I add a simple shading rule like this:

```
assemblyShadeRules in assembly ++= Seq(
  ShadeRule.rename("com.typesafe.config.**" -> "my_config.@1")
    .inLibrary("com.typesafe" % "config" % "1.3.0")
    .inProject
)
```
It ends up deleting my entire project code in the assembled JAR.
Is anyone else experiencing this?

**Comment by dragos** [comment] 2016-04-06 12:00
*Petit* update: the issue only happens on Windows. I also see error output like this one:

```
Fully-qualified classname does not match jar entry:
  jar entry: com\typesafe\config\impl\SimpleIncluder.class
  class name: com/typesafe/config/impl/SimpleIncluder.class
Omitting com\typesafe\config\impl\SimpleIncluder.class.
Fully-qualified classname does not match jar entry:
  jar entry: com\typesafe\config\impl\SubstitutionExpression.class
  class name: com/typesafe/config/impl/SubstitutionExpression.class
Omitting com\typesafe\config\impl\SubstitutionExpression.class.
```

**Comment by YuvalItzchakov** [comment] 2016-04-06 12:16
So a complete summary of the problem:

System: Windows 8.1, sbt 0.3.11, sbt-assembly 0.14.2

Adding any shading rules causes SBT to completely remove project code from the uber JAR.

Reproduce: Take https://github.com/dragos/SimpleBugReproduce and build it on a Windows machine.
Run jar -tf on the assembly and see there's no shading of "com.typesafe.config", it's completely removed.  In my case (a bit more complex), the entire project code goes missing too.

**Comment by YuvalItzchakov** [comment] 2016-04-06 20:09
Fixed with PR. I think we can close this.

**Closed** 2020-05-24 18:53 UTC
